- README.md
- Closes #3 
1. README 수정
이 PR은 스크린샷이 없습니다.
> [TEST] 테스트

- src/main/java/com/example/epari/assignment/controller/AssignmentController.java
- src/main/java/com/example/epari/assignment/dto/AssignmentRqDto.java
- src/main/java/com/example/epari/assignment/repository/AssignmentRepository.java
- src/main/java/com/example/epari/assignment/service/AssignmentService.java
- Closes #14 
AssignmentController, AssignmentRepository, AssignmentService 추가
|기능|스크린샷|
|---|---|
|과제추가|<img width="400" alt="image" src="https://github.com/user-attachments/assets/a892baef-58d6-4e37-9b1f-0f4f19363144">|
|과제전체조회|<img width="400" alt="image" src="https://github.com/user-attachments/assets/d71d3159-720c-48c9-9ea7-2abfdae51d12">|
|과제검색조회|<img width="400" alt="image" src="https://github.com/user-attachments/assets/bc41196c-05d5-4ed3-b0fc-19a175594b53">|
|과제수정|<img width="400" alt="image" src="https://github.com/user-attachments/assets/c4379323-5bc0-4e36-aad9-80801296ad37">|
|과제삭제|<img width="400" alt="image" src="https://github.com/user-attachments/assets/0d355d12-97af-42b2-a9e4-03190f221bec">|
> [FEAT] 과제 기본 CRUD api 구현

- build.gradle
- src/main/java/com/example/epari/global/auth/controller/AuthController.java
- src/main/java/com/example/epari/global/config/security/SecurityConfig.java
- Closes #13 
1. Spring Security와 AWS Cognito 연동 구현
- Spring Security, Resource Server, Cognito 관련 AWS SDK 의존성 추가
- SecurityConfig 구성
- CORS 설정 적용
- JWT 토큰에서 Cognito 그룹 Claim 추출 기능 구현
- 추출된 그룹 정보를 활용한 권한 부여 로직 구현
2. 토큰 인증 기능 구현
- AuthController 추가 및 `/validate` 엔드포인트 구현
- Spring Security JWT 검증 방식으로 개선
- 토큰 검증 응답에 사용자명과 Cognito 그룹 정보 포함
3. 개발 편의를 위한 임시 보안 설정
- 현재 단계에서 모든 엔드포인트 접근 허용 (permitAll)
- 기존 /api/auth/** 관련 설정 제거
|기능|스크린샷|
|---|---|
|로그인|![학생 로그인 화면](https://github.com/user-attachments/assets/1773bcce-419c-4a95-a716-8e64f2ffbc52)|
- 현재는 개발의 편의를 위해 모든 엔드포인트 접근을 허용한 상태입니다.
- 추후 RABC 설정 및 보안 설정을 위한 리팩토링을 진행 예정입니다.
> [FEAT] Cognito를 적용한 일반 로그인 기능 구현

- src/main/java/com/example/epari/global/annotation/CurrentUserEmail.java
- src/main/java/com/example/epari/global/config/security/SecurityConfig.java
- Closes #20 
1. 역할 기반 접근 제어를 위한 URL 기반 보안 적용
2. CurrentUserEmail 커스텀 어노테이션 추가
- JWT의 이메일 claim 추출을 위한 어노테이션
관련 내용을 문서화하여 추후 공유할 예정입니다.
> [FEAT] 사용자 역할 기반 접근 제어 설정

- .gitignore
- Dockerfile
- build.gradle
- src/main/java/com/example/epari/assignment/controller/AssignmentController.java
- src/main/java/com/example/epari/global/config/security/CorsProperties.java
- src/main/java/com/example/epari/global/config/security/SecurityConfig.java
- src/main/resources/application-prod.yaml
- src/main/resources/application.properties
- src/main/resources/application.yaml
- Closes #40 
1. CORS 설정 개선
- 불필요한 @crossorigin 어노테이션 제거
- CORS Origin 정보를 yaml 파일로 추출
- CorsProperties 클래스 추가 및 SecurityConfig 연동
2. 설정 파일 구조 개선
- application.properties를 application.yaml로 마이그레이션
- application-dev.yaml 파일 Git 추적 제외 처리
- 프로덕션용 application-prod.yml 추가
- AWS SDK 설정
- 로깅 레벨 구성
- JPA 및 파일 업로드 설정
- 환경변수 사용 위치 문서화
3. 모니터링 설정 추가
- Spring Actuator 의존성 추가
- 헬스체크 엔드포인트 접근 허용 설정
4. 도커라이즈 환경 구성
- 멀티 스테이지 빌드 적용 (JDK -> JRE)
- 빌드 캐시 최적화
- JVM 및 컨테이너 환경 최적화
- 타임존 설정 (Asia/Seoul)
1. 프로덕션 배포 시 application-prod.yml의 환경변수 값들을 적절히 설정해주어야 합니다.
2. 도커 이미지 빌드 시 계층화된 구조로 인해 빌드 시간이 최적화되었습니다.
> [REFACTOR] 배포를 위한 코드 리팩토링(CORS Origin, properties 파일 등)

- src/main/java/com/example/epari/assignment/controller/AssignmentController.java
- src/main/java/com/example/epari/assignment/repository/AssignmentRepository.java
- src/main/java/com/example/epari/assignment/service/AssignmentService.java
- Closes #48 
1. 과제 목록 API 연결
- 프론트엔드와의 과제 목록 기능을 위한 API를 구현하고 연결
- @PathVariable 어노테이션을 통해 주소에서 courseId 가져오기
- /api/courses/{courseId}/assignments 엔드포인트를 통해 과제 정보를 제공
> [FEAT] 과제 리스트 조회 및 과제 출제 구현

- src/main/java/com/example/epari/assignment/controller/AssignmentController.java
- src/main/java/com/example/epari/assignment/domain/Assignment.java
- src/main/java/com/example/epari/assignment/dto/assignment/AssignmentResponseDto.java
- src/main/java/com/example/epari/assignment/repository/AssignmentRepository.java
- src/main/java/com/example/epari/assignment/service/AssignmentService.java
- Closes #51 
1. 상세페이지 개선
- AssignmentController 로직 개선: 강사 정보 활용 및 컨트롤러 구조 최적화
- AssignmentService 로직 개선: 강사 이름 출력 로직 추가
- Assignment 엔티티에 필드 추가: 작성자 정보 저장을 위해 일부 필드 추가
2. 목록페이지 개선
- 과제 목록 페이지에 작성자 정보 출력 로직 개선
|기능|스크린샷|
|---|---|
|컨트롤러 개선|<img width="401" alt="image" src="https://github.com/user-attachments/assets/6d02ae30-de0b-459c-a3e9-b9fe8f9bc253">|
|엔티티 추가|<img width="367" alt="image" src="https://github.com/user-attachments/assets/64b9d606-ec4e-43aa-977d-4513c18e2664">|
|빌더 추가|<img width="445" alt="image" src="https://github.com/user-attachments/assets/575922c5-1dd2-4fa8-88fc-1ab8347ced9a">|
> [Refactor] 과제 상세 조회, 목록 로직 개선

- src/main/java/com/example/epari/global/config/aws/AwsS3Properties.java
- Closes #68 
1. S3 설정값을 주입하는 어노테이션 추가
|기능|스크린샷|
|---|---|
|@Value의존성추가|<img width="432" alt="image" src="https://github.com/user-attachments/assets/68958983-7686-4191-8123-653af3d6198a">|
> [REFACTOR] S3 설정값 주입 어노테이션 추가

- src/main/java/com/example/epari/global/config/aws/AwsS3Properties.java
- Closes #72 
@Value안에 잘못된 경로 설정으로 인한 오류 해결을 위함과 불필요해서 삭제했습니다.
|기능|스크린샷|
|---|---|
|변경 후 |<img width="433" alt="image" src="https://github.com/user-attachments/assets/6716382d-90d9-435c-8500-c7b1d5d60405">|
> [FIX] S3 설정 주입 어노테이션 제거

- src/main/java/com/example/epari/board/controller/FileController.java
- src/main/java/com/example/epari/board/controller/NoticeController.java
- src/main/java/com/example/epari/board/service/NoticeService.java
- Closes #70 
이 PR에서는 프론트와 연동 시 데이터를 제대로 불러오지 못하는 오류가 있어서
일부 백엔드 코드를 개선하였습니다
|기능|스크린샷|
|---|---|
|수정|![image](https://github.com/user-attachments/assets/ff80263a-85c1-46cc-9710-bdb86748227a)|
|프론트와 연동|![스크린샷 2024-11-16 163128](https://github.com/user-attachments/assets/8c7d7b5b-f983-40bc-9eec-6ba486517a32)![스크린샷 2024-11-16 163154](https://github.com/user-attachments/assets/9b8255b6-d6c5-482d-a507-cb38b3f63754)|z
프론트와의 연동 시 오류가 있을 경우 백엔드 코드 수정
> [FEAT] 공지사항 프론트와 연동 시 기능 개선

- src/main/java/com/example/epari/assignment/controller/AssignmentController.java
- src/main/java/com/example/epari/assignment/controller/SubmissionController.java
- src/main/java/com/example/epari/assignment/controller/SubmissionFileController.java
- src/main/java/com/example/epari/assignment/domain/AssignmentFile.java
- src/main/java/com/example/epari/assignment/domain/Submission.java
- src/main/java/com/example/epari/assignment/domain/SubmissionFile.java
- src/main/java/com/example/epari/assignment/dto/file/SubmissionFileResponseDto.java
- src/main/java/com/example/epari/assignment/dto/submission/GradeRequestDto.java
- src/main/java/com/example/epari/assignment/dto/submission/SubmissionRequestDto.java
- src/main/java/com/example/epari/assignment/dto/submission/SubmissionResponseDto.java
- src/main/java/com/example/epari/assignment/repository/SubmissionFileRepository.java
- src/main/java/com/example/epari/assignment/repository/SubmissionRepository.java
- src/main/java/com/example/epari/assignment/service/AssignmentService.java
- src/main/java/com/example/epari/assignment/service/SubmissionService.java
- src/main/java/com/example/epari/user/repository/StudentRepository.java
- src/test/resources/application.properties
- src/test/resources/application.yaml
- Closes #83 
1. `SubmissionController, SubmissionFileController, SubmissionService` 서비스 로직 구현
- 제출 CRUD 및 강사 Grade, Feedback 구현
2. `SubmissionReuestDto, SubmissionResponseDto` 구현
3. `GradeRequestDto` 로직 작성 --> 학생이 제출한 과제를 강사가 채점하기 위한 RequestDto
4. `Submission` -> 엔티티 필드 description 어노테이션 `@Lob` 제거 -> `@column(columnDefinition = "LONGTEXT")` 변경
수정, 파일 제거 메서드 추가
5. 'AssignmentController, AssignmentService` 기존 parameter로 instructorId를 사용하던 로직을 보안 강화를 위해
`@CurrentUserEmail` 어노테이션을 이용하는 로직으로 변경
|기능|스크린샷|
|---|---|
|제출|<img width="600" alt="image" src="https://github.com/user-attachments/assets/61c0d1b8-ca76-4699-8aa2-f16abe39f55b">|
|기능|스크린샷|
|---|---|
|삭제|<img width="600" alt="image" src="https://github.com/user-attachments/assets/63839926-a219-42bc-b2dd-073a8b394251">|
|기능|스크린샷|
|---|---| …
> [FEAT] 과제 제출 관련 서비스 로직 구현

- src/main/java/com/example/epari/course/controller/CourseContentController.java
- src/main/java/com/example/epari/course/controller/CourseController.java
- src/main/java/com/example/epari/global/config/security/SecurityConfig.java
- Closes #77 
1. 강의 자료 업로드 API 구조 개선
- @RequestParam 방식에서 @ModelAttribute DTO 방식으로 변경
- 업로드 날짜 자동 설정 로직 추가
2. 보안 설정 최적화
- SecurityConfig에 메서드 수준 보안 설정 추가
- 컨트롤러의 중복 보안 설정 제거
- @PreAuthorize 어노테이션 활성화
3. 코드 정리
- 불필요한 import 문 제거
- 중복 어노테이션 정리
> [REFACTOR] 업로드 코드 개선 및 @EnableMethodSecurity 설정 변경

- docker-compose.yml
- src/main/java/com/example/epari/global/config/AsyncConfig.java
- src/main/java/com/example/epari/user/controller/UserProfileController.java
- src/main/java/com/example/epari/user/service/UserProfileService.java
- Closes #95 
1. **비동기 처리 설정**  
- `ThreadPoolTaskExecutor`를 활용하여 커스텀 비동기 실행기 구현  
- 코어 및 최대 스레드 수, 큐 용량, 스레드 이름 접두어 설정  
2. **프로필 이미지 업로드 및 삭제 기능**  
- AWS S3를 이용한 이미지 업로드 및 삭제 처리 추가  
- 사용자 프로필 이미지 업로드 및 삭제 API 엔드포인트 구현  
- 삭제 요청 시 비동기 처리로 응답 성능 최적화  
3. **사용자 프로필 관리 서비스**  
- Cognito 사용자 속성에 프로필 이미지 URL 저장 및 업데이트 로직 추가  
4. **Redis 컨테이너 설정**  
- 이미지 URL 캐싱을 위한 Redis 컨테이너 설정 추가  
|기능|스크린샷|
|---|---|
|프로필 사진 업로드|![백엔드 S3 프로필 사진 변경 시](https://github.com/user-attachments/assets/4f9aab76-8ca2-4a73-ab94-de418faf2d65)|
|프로필 사진 변경|![백엔드 S3 프로필 사진 변경 시](https://github.com/user-attachments/assets/57900351-64bb-4ccb-9b08-7497c82e91c2)|
|프로필 사진 삭제|![백엔드 S3 프로필 사진 삭제 시](https://github.com/user-attachments/assets/18122e0c-1c79-4f21-9078-cd0a6921572b)|
> 마이페이지 프로필 이미지 관리 및 비동기 처리 개선

- src/main/java/com/example/epari/admin/service/AdminUserService.java
- src/main/java/com/example/epari/assignment/controller/CourseSubmissionController.java
- src/main/java/com/example/epari/assignment/controller/SubmissionController.java
- src/main/java/com/example/epari/assignment/domain/Submission.java
- src/main/java/com/example/epari/assignment/dto/assignment/AssignmentResponseDto.java
- src/main/java/com/example/epari/assignment/dto/submission/SubmissionResponseDto.java
- src/main/java/com/example/epari/assignment/repository/SubmissionRepository.java
- src/main/java/com/example/epari/assignment/service/SubmissionService.java
- src/main/java/com/example/epari/course/dto/course/CourseResponseDto.java
- src/main/java/com/example/epari/global/common/base/BaseUser.java
- src/main/java/com/example/epari/global/common/enums/SubmissionGrade.java
- src/main/java/com/example/epari/global/init/InitDataLoader.java
- src/main/java/com/example/epari/user/domain/Instructor.java
- src/main/java/com/example/epari/user/domain/Student.java
- #98 
1. `Submission` SubmissionStatus 기본 상태를 SUBMITTED로 변경
2. `SubmissionController` 특정 과제의 전체 학생 제출물 조회 GetMapping 구현
3. `SubmissionRepository, SubmissionService` 특정 과제의 전체 학생 제출물 조회
4. `CourseSubmissionController` 특정 강의의 전체 제출물 조회
CourseSubmissionController
|기능|스크린샷|
|---|---|
|포스트맨|<img width="1016" alt="image" src="https://github.com/user-attachments/assets/5861e4bb-9ae1-4ee4-9d42-b99f87ced5f4">|
@cuteJJong `CourseSubmissionController` 이용하시면 됩니다
> [FEAT] 과제 제출물 조회 서비스 로직 구현

- src/main/java/com/example/epari/admin/service/AdminCourseService.java
- src/main/java/com/example/epari/admin/service/AdminCourseStudentService.java
- Closes #122 
1. @CacheEvict 어노테이션의 속성 allEntries = true를 key 직접 지정 방식으로 변경
> [FIX] @CacheEvict 관련 문제 해결

- src/main/java/com/example/epari/EpariBackendApplication.java
- src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
- src/main/java/com/example/epari/exam/controller/GradingController.java
- src/main/java/com/example/epari/exam/domain/Exam.java
- src/main/java/com/example/epari/exam/dto/common/ExamResultSummaryDto.java
- src/main/java/com/example/epari/exam/dto/response/ExamSummaryDto.java
- src/main/java/com/example/epari/exam/repository/ExamRepository.java
- src/main/java/com/example/epari/exam/service/ExamStatusService.java
- src/main/java/com/example/epari/exam/service/ExamSubmissionService.java
- src/main/java/com/example/epari/exam/service/GradingService.java
- src/main/java/com/example/epari/global/common/enums/ExamStatus.java
- src/main/resources/application.yaml
- Closes #119 
**1. 학생의 시험 상태 기본 값을 미제출로 설정**
- ExamSummaryDto의 필드 초기값을 `null`에서 `NOT_SUBMITTED`로 설정하여 상태 초기화를 명확히 구현
**2. ExamRepository에 상태 조회 쿼리 추가**
- 상태별 시험 목록을 조회할 수 있는 메서드 `findByStatus`, `findByStatusIn` 추가
**3. Exam 엔티티에 상태 변경 로직 추가**
- `updateStatus` 메서드를 구현하여 상태를 동적으로 변경 가능
- 상태 검증 메서드 `canChangeStatusTo`로 변경 가능 여부를 사전에 확인하도록 설정
**4. Exam 상태에 따른 채점 및 결과 매핑 로직 수정**
- ExamStatusService 상태 기반 제출 및 채점 관리 로직 분리 및 구현
- `checkAndUpdateExamStatus`로 1분 간격으로 시험 상태를 확인 및 갱신
- `processExamEndWithNewTransaction`로 미제출자를 강제 제출 처리
- `startGradingProcess` 자동 채점 처리
- `finalizeExam` 시험 종료 처리
- GradingService: 채점 로직 개선 및 예외 처리 강화
- `processGrading`에 시험 채점 프로세스 수정
- ExamSubmissionService에서 학생 결과를 정확히 매핑하도록 로직 보완 `getExamResults ` 메서드 수정
- `submitAnswer`에 상태 검증 로직 추가
**5. 답안 비교를 위한 …
> [FEAT] 시험을 미응시한 학생의 결과도 조회 가능하도록 로직 수정

- src/main/java/com/example/epari/assignment/dto/submission/SubmissionResponseDto.java
- src/main/java/com/example/epari/exam/controller/ExamSubmissionController.java
- src/main/java/com/example/epari/exam/controller/GradingController.java
- src/main/java/com/example/epari/exam/dto/common/ExamResultSummaryDto.java
- src/main/java/com/example/epari/exam/dto/common/QuestionResultDto.java
- src/main/java/com/example/epari/exam/service/ExamSubmissionService.java
- Close #120 
1. SubmissionResponseDto 과제 정보 추가
2. 상세 시험 조회 기능 구현
> [REFACTOR] 과제 전체 조회 제목 정보 추가

- src/main/java/com/example/epari/global/auth/controller/AuthController.java
- src/main/java/com/example/epari/global/auth/service/AuthService.java
- Closes #118
1. Cognito 사용자 그룹 관리 기능 개선
- PENDING_ROLES 그룹 추가 API 엔드포인트 구현
- 사용자 이메일 기반 그룹 할당 로직 구현
- 그룹 추가 결과에 대한 응답 처리
2. 사용자 검색 로직 개선
- 이메일과 username을 모두 포함하는 검색 필터 적용
- 중복 그룹 할당 방지를 위한 사전 검증 로직 추가
- 사용자 검색 실패 시 예외 처리 구현
- Cognito 사용자 풀에서 사용자 검색 시 이메일과 username 모두를 고려하여 검색하도록 개선되었습니다.
- PENDING_ROLES 그룹에 사용자 추가 시 중복 검사가 이루어지도록 하여 안정성이 향상되었습니다.
- 스크린샷은 추후 첨부하겠습니다. 
-
> [FEAT] Google 로그인 기능 구현 

- src/main/java/com/example/epari/exam/service/ExamService.java
- Closes #127 
- ExamService에 calculateExamStatistics 응시 인원 조회 상태값 Completed 추가
|기능|스크린샷|
|---|---|
|기능명|<img width="916" alt="스크린샷 2024-11-22 오후 1 18 31" src="https://github.com/user-attachments/assets/e306de8a-2ab8-4007-b16c-d99bea872d6f">|
> [FIX] 시험 응시 인원 조회 상태값 추가

- src/main/java/com/example/epari/assignment/service/SubmissionService.java
> [FIX] 테스트 빌드 에러 수정

- src/main/java/com/example/epari/global/init/InitDataLoader.java
- Closes #146 
공지사항과 강의 공지사항 데이터를 init data에 추가하였습니다.
|기능|스크린샷|
|---|---|
|기능명|![image](https://github.com/user-attachments/assets/a3589b9b-9608-479c-867f-767d6da541a0)|
> [FEAT] 공지사항 init data 추가

- src/main/java/com/example/epari/global/auth/controller/AuthController.java
- src/main/java/com/example/epari/global/auth/service/AuthService.java
- Closes #158 
1. Lambda 트리거 관련 코드 정리
- `addUserToPendingRole` 메소드 제거 (Lambda로 대체)
- `/api/auth/first-login` 엔드포인트 제거
- `signUp` 메소드에서 PENDING_ROLES 할당 로직 제거
2. 기능 개선
- Google 프로필 이미지 업데이트 로직 구현
- 사용자 그룹 조회 및 토큰 검증 로직 강화
- 이메일 인증 및 사용자 속성 관리 기능 개선
3. 예외 처리
- 사용자 검증 및 그룹 관리 관련 예외 처리 강화
- 에러 로깅 개선
- Lambda 트리거가 PENDING_ROLES 그룹 할당을 담당
```javascript
// 기존 코드에서 제거된 부분
public void addUserToPendingRole(String email) {
// Lambda 트리거로 대체
}
```
- 성능 개선: API 호출 방식(1.22s) → Lambda 트리거(421.58ms)
> [FIX] Lambda 트리거를 활용한 사용자 인증 로직 개선
